name = "Oracle"
uuid = "7240a794-28ba-5199-b477-df5fe5cf6155"
license = "MIT"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
version = "0.0.6"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
